# Generated by Django 5.1.7 on 2025-03-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='distance_miles',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='dropoff_delay',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='trip',
            name='fuel_stops',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_delay',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='trip',
            name='rest_stops',
            field=models.IntegerField(default=0),
        ),
    ]
