# Generated by Django 5.1.7 on 2025-03-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_driverprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='truck_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
    ]
